name: DayNight
main: elconguyenvuong\daynight\DayNight
src-namespace-prefix: elconguyenvuong\daynight
api: 5.0.0
version: 0.0.1
author: ElcoNguyenVuong

permissions:
  daynight.command.use:
    default: op
